### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by NervoxNight** [open-goal/launcher#533] opened 2024-08-11 17:15 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Describe the Bug

When I click on my ISO file (Jack 1), it starts to extract and verify it then the following error appears:

Unexpected error occured with code -1073740791

### How To Reproduce

Select the ISO file, and wait the process

### Operating System

Windows

### Launcher Version

2.4.9

### Tooling Version

0.2.15

**Comment by xTVaser** [comment] 2024-08-11 17:19
Include your support package.  But this is often caused by an ISO file that was made in a way that our code doesn't like.  It's more a `jak-project` issue than a launcher one.

**Comment by xTVaser** [comment] 2024-08-11 22:36
Duplicate of a discord help thread - https://discord.com/channels/756287461377703987/1272245695448875040

**Closed as completed by xTVaser** 2024-08-11 22:36 UTC
Labels: bug
